ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Asciidoc converter
:icons: font

IMPORTANT: Tested with _Maven 3.5.0, JDK 8, Kotlin 1.1.51_

== Backend

You can specify _backend_ by passing `backend` _java system property_

== Generated files output directory

IMPORTANT: If `outputDir` java system property not defined, output files will
be generated next to input asciidoc files

== Modes

IMPORTANT: Application will fallback to _FILES_ mode if no other valid mode specified

* FILES
+
[source,bash]
java [-Dmode=FILES] -Dfiles=FULL_FILE_PATH1[,FULL_FILE_PATH2,FULL_FILE_PATH3...] [-DoutputDir=YOUR_DIR_HERE] -jar app.jar

* DIRECTORIES
+
[source,bash]
java -Dmode=DIRECTORIES [-DoutputDir=YOUR_DIR_HERE] -jar app.jar

== Packaging app

[source,bash]
mvn clean package

== Running app

[source,bash]
java -Dmode=DIR -Ddirs=FULL_PATH_OF_DIR_CONTAINING_ADOC_FILES \
    -DoutputDir=FULL_PATH_OF_DIR_CONTAINING_GENERATED_OUTPUT \
    -jar asciidoc-converter-1.0-SNAPSHOT-jar-with-dependencies.jar