ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Asciidoc converter
:icons: font
:jar-name: converter-1.0.jar-jar-with-dependencies.jar

IMPORTANT: Tested with _Maven 3.5.0, JDK 8, Kotlin 1.1.51_

== Packaging app

[source,bash]
----
mvn clean package#<1>
----
<1> This will generate {jar-name} in `target` dir

== Backend

You can specify _backend_ by passing `backend` _java system property_ when running the application

== Generated files output directory

If `outputDir` java system property not defined, output files will
be generated next to input asciidoc files

== Running the app in different modes

Application will fallback to _FILES_ mode if no other valid mode specified

* FILES mode
+
[source,bash,subs=normal]
java [-Dmode=FILES] \
    -Dfiles=FULL_FILE_PATH1[,FULL_FILE_PATH2,FULL_FILE_PATH3...] \
    [-DoutputDir=YOUR_DIR_HERE] \
    -jar {jar-name}

* DIRECTORIES mode
+
[source,bash,subs=normal]
java -Dmode=DIR -Ddirs=FULL_PATH_OF_DIR_CONTAINING_ADOC_FILES \
    -DoutputDir=FULL_PATH_OF_DIR_CONTAINING_GENERATED_OUTPUT \
    -jar {jar-name}

